name: Go package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
          cache: true

      - name: build
        if: ${{ github.ref == 'refs/heads/master' }}
        run: |
          make push
          tree .build
        env:
          GOPATH: /home/runner/go
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: release
        if: ${{ github.ref == 'refs/heads/master' }}
        run: |
          make release
        env:
          GOPATH: /home/runner/go
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: update helm chart
        if: ${{ github.ref == 'refs/heads/master' }}
        run: |
          make helm-push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
