name: ChartRelease
on: [push]

env:
  CHART_NAME: kafka-exporter
jobs:
  release:
    runs-on: ubuntu-latest
    name: 'package'
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      -
        run: |
          echo "CHART=${{ env.CHART_NAME }}" >> $GITHUB_ENV
          echo "VERSION=1.$(date +'%Y%m%d').${GITHUB_RUN_NUMBER}" >> $GITHUB_ENV
          echo "RELEASE_TAG=${CHART}-${VERSION}" >> $GITHUB_ENV
      -
        name: helm package
        run: |
          helm package charts/${env.CHART} --dependency-update --version ${env.VERSION} --destination target
      -
        name: Release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          tag: "${{ env.RELEASE_TAG }}"
          commit: "${{ env.GITHUB_SHA }}"
          artifacts: "target/*.tgz"
          body: "Release from PR merge"
          token: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Log into GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | helm registry login https://ghcr.io -u ${{ github.actor }} --password-stdin
      -
        name: Push chart to ghcr
        run: |
          CHART=${{ steps.match-chart-update.outputs.group1 }}
          VERSION="1.$(date +'%Y%m%d').${GITHUB_RUN_NUMBER}"
          helm push target/${env.RELEASE_TAG}.tgz oci://ghcr.io/${OWNER_LC}/devops-charts